schema_version = "1.0.0"

id = "quakeblend"
version = "0.1.0"
name = "QuakeBlend"
tagline = "Import Quake 1/2/3 maps, BSPs, and texture archives"
maintainer = "QuakeBlend Contributors"
type = "add-on"

website = "https://github.com/Tzeentchnet/QuakeBlend"

tags = ["Import-Export"]

blender_version_min = "5.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2026 QuakeBlend Contributors",
]
